version: '3'

volumes:
  db:
    driver: local

services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: thisisasecret
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0 --port=33066
    volumes:
      - db:/var/lib/mysql
    ports:
      - 33066:33066
