GuidanceGroup.create!({"id"=>6, "name"=>"McMaster", "org_id"=>10, "optional_subset"=>true, "published"=>true})
GuidanceGroup.create!({"id"=>11, "name"=>"McGill", "org_id"=>13, "optional_subset"=>false, "published"=>true})
GuidanceGroup.create!({"id"=>13, "name"=>"University of Guelph ", "org_id"=>22, "optional_subset"=>false, "published"=>true})
GuidanceGroup.create!({"id"=>15, "name"=>"Simon Fraser University DMP", "org_id"=>14, "optional_subset"=>false, "published"=>true})
GuidanceGroup.create!({"id"=>17, "name"=>"University of Lethbridge", "org_id"=>28, "optional_subset"=>false, "published"=>true})
GuidanceGroup.create!({"id"=>18, "name"=>"Test guidance group - UdeM", "org_id"=>32, "optional_subset"=>false, "published"=>true})
GuidanceGroup.create!({"id"=>19, "name"=>"Concordia University Guidance", "org_id"=>12, "optional_subset"=>false, "published"=>true})
GuidanceGroup.create!({"id"=>20, "name"=>"Alliance/FfT", "org_id"=>22, "optional_subset"=>false, "published"=>true})
GuidanceGroup.create!({"id"=>22, "name"=>"UQAM", "org_id"=>29, "optional_subset"=>false, "published"=>true})
GuidanceGroup.create!({"id"=>23, "name"=>"Université du Québec à Trois-Rivières", "org_id"=>42, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>24, "name"=>"Directives de l'INRS", "org_id"=>53, "optional_subset"=>false, "published"=>true})
GuidanceGroup.create!({"id"=>25, "name"=>"OTHER", "org_id"=>59, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>26, "name"=>"WLU", "org_id"=>60, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>27, "name"=>"AU", "org_id"=>61, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>28, "name"=>"MacEwan", "org_id"=>62, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>29, "name"=>"Hakai Institute", "org_id"=>63, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>30, "name"=>"StFX", "org_id"=>64, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>31, "name"=>"USB", "org_id"=>65, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>32, "name"=>"UQO", "org_id"=>66, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>33, "name"=>"Sheridan", "org_id"=>67, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>34, "name"=>"CHUSJ", "org_id"=>68, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>35, "name"=>"Université Laval conseils", "org_id"=>44, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>36, "name"=>"Portage Network", "org_id"=>8, "optional_subset"=>true, "published"=>true})
GuidanceGroup.create!({"id"=>37, "name"=>"Western Guidance", "org_id"=>27, "optional_subset"=>true, "published"=>false})
GuidanceGroup.create!({"id"=>39, "name"=>"U of T Libraries", "org_id"=>20, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>40, "name"=>"Test", "org_id"=>8, "optional_subset"=>true, "published"=>false})
GuidanceGroup.create!({"id"=>41, "name"=>"TestOrg", "org_id"=>69, "optional_subset"=>false, "published"=>true})
GuidanceGroup.create!({"id"=>42, "name"=>"TestSchool", "org_id"=>69, "optional_subset"=>true, "published"=>false})
GuidanceGroup.create!({"id"=>43, "name"=>"UWindsor", "org_id"=>70, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>44, "name"=>"UR", "org_id"=>71, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>45, "name"=>"UW", "org_id"=>72, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>46, "name"=>"CUE", "org_id"=>73, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>47, "name"=>"Cégep de Sherbrooke", "org_id"=>74, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>48, "name"=>"ÉTS / ETS", "org_id"=>75, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>49, "name"=>"MTA", "org_id"=>76, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>50, "name"=>"LakeheadU", "org_id"=>77, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>51, "name"=>"RDP", "org_id"=>78, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>52, "name"=>"NSCC", "org_id"=>87, "optional_subset"=>false, "published"=>false})
GuidanceGroup.create!({"id"=>53, "name"=>"Portage", "org_id"=>8, "optional_subset"=>false, "published"=>false})
Theme.create!({"id"=>37, "title"=>"Data Collection", "description"=>"This section addresses data collection issues such as data types, file formats, naming conventions, and data organization – factors that will improve the usability of your data and contribute to the success of your project.\n", "locale"=>nil})
Theme.create!({"id"=>38, "title"=>"Documentation and Metadata", "description"=>"Because data are rarely self-explanatory, all research data should be accompanied by metadata (information that describes the data according to community best practices).  Metadata standards vary across disciplines, but generally state who created the data and when, how the data were created, their quality, accuracy, and precision, as well as other features necessary to facilitate data discovery, understanding and reuse. Any restrictions on use of the data must be explained in the metadata, along with information on how to obtain approved access to the data, where possible.", "locale"=>nil})
Theme.create!({"id"=>39, "title"=>"Storage and Backup", "description"=>"Planning how research data will be stored and backed up throughout and beyond a research project is critical in ensuring data security and integrity. Appropriate storage and backup not only helps protect research data from catastrophic losses (due to hardware and software failures, viruses, hackers, natural disasters, human error, etc.), but also facilitates appropriate access by current and future researchers.", "locale"=>nil})
Theme.create!({"id"=>40, "title"=>"Preservation", "description"=>"Data preservation will depend on potential reuse value, whether there are obligations to either retain or destroy data, and the resources required to properly curate the data and ensure that it remains usable in the future. In some circumstances, it may be desirable to preserve all versions of the data (e.g. raw, processed, analyzed, final), but in others, it may be preferable to keep only selected or final data (e.g. transcripts instead of audio interviews)", "locale"=>nil})
Theme.create!({"id"=>41, "title"=>"Sharing and Reuse", "description"=>"Most Canadian research funding agencies now have policies requiring research data to be shared upon publication of the research results or within a reasonable period of time. While data sharing contributes to the visibility and impact of research, it has to be balanced with the legitimate desire of researchers to maximise their research outputs before releasing their data. Equally important is the need to protect the privacy of respondents and to properly handle sensitive data.", "locale"=>nil})
Theme.create!({"id"=>42, "title"=>"Responsibilities and Resources", "description"=>"Data management focuses on the 'what' and 'how' of operationally supporting data across the research lifecycle.  Data stewardship focuses on 'who' is responsible for ensuring that data management happens. A large project, for example, will involve multiple data stewards. The Principal Investigator should identify at the beginning of a project all of the people who will have responsibilities for data management tasks during and after the project.", "locale"=>nil})
Theme.create!({"id"=>43, "title"=>"Ethics and Legal Compliance", "description"=>"Researchers and their teams need to be aware of the policies and processes, both ethical and legal, to which their research data management must comply. Protection of respondent privacy is of paramount importance and informs many data management practices.  In their data management plan, researchers must state how they will prepare, store, share, and archive the data in a way that ensures participant information is protected, throughout the research lifecycle, from disclosure, harmful use, or inappropriate linkages with other personal data. It's recognized that there may be cases where certain data and metadata cannot be made public for various policy or legal reasons, however, the default position should be that all research data and metadata are public.", "locale"=>nil})
