# frozen_string_literal: true

require_relative "boot"

require "rails/all"

require "csv"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module DMPRoadmap

  class Application < Rails::Application
    # Set dmp_core version here
    config.x.app_version = "2025.11" 

    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 5.2

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration can go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded after loading
    # the framework and any gems in your application.

    # --------------------------------- #
    # OVERRIDES TO DEFAULT RAILS CONFIG #
    # --------------------------------- #

    # Rails 6+ adds middleware to prevent DNS rebinding attacks:
    #    https://guides.rubyonrails.org/configuring.html#actiondispatch-hostauthorization
    #
    # This allows us to define the hostname and add it to the whitelist. If you attempt
    # to access the site and receive a 'Blocked host' error then you will need to
    # set this environment variable
    # config.hosts << '.lvh.me'
    # hosts.each { |host| config.hosts << host }

    # config.hosts << ENV['DMPROADMAP_HOST'] if ENV['DMPROADMAP_HOST'].present?

    hosts = ENV.fetch('DMPROADMAP_HOSTS').split(',')
    hosts.each { |host| Rails.application.config.hosts << host }

    config.logger = ActiveSupport::Logger.new("log/#{Rails.env}.log", "daily")

    config.autoload_paths += %W[#{config.root}/lib]

    # HTML tags that are allowed to pass through `sanitize`.
    config.action_view.sanitized_allowed_tags = %w[
      p br strong em a table thead tbody tr td th tfoot caption ul ol li
    ]

    # Configure sensitive parameters which will be filtered from the log file.
    config.filter_parameters += [:password]

    # Enable escaping HTML in JSON.
    config.active_support.escape_html_entities_in_json = true

    # Allow controllers to access view helpers
    # TODO: We should see what methods specifically are used by the controllers
    #       and include them specifically in the controllers. We should also consider
    #       moving our helper methods into Presenters if it makes sense
    config.action_controller.include_all_helpers = true

    # Set the default host for mailer URLs
    #config.action_mailer.default_url_options = { host: Socket.gethostname.to_s }
    # config.action_mailer.default_url_options = { host: "https://dmp_core.dcc.ac.uk" }
    config.action_mailer.default_url_options = { host: ENV["HOST_URL"] }


    Rails.application.config.assets.configure do |env|
      env.export_concurrent = false
    end

    #_dmproadmap.rb settings
    # --------------------- #
    # ORGANISATION SETTINGS #
    # --------------------- #

    # Your organisation name, used in various places throught the application
    config.x.organisation.name = ENV['ORGANISATION_NAME']
    # Your organisation's abbreviation
    config.x.organisation.abbreviation = ENV['ORGANISATION_ABBREVIATION']
    # Your organisation's homepage, used in some of the public facing pages
    config.x.organisation.url = ENV['ORGANISATION_URL']
    # Your organisation's legal (official) name - used in the copyright portion of the footer
    config.x.organisation.copywrite_name = ENV['ORGANISATION_COPYWRITE_NAME']
    # This email is used as the 'from' address for emails generated by the application
    config.x.organisation.email = ENV['ORGANISATION_EMAIL']
    # This email is used as the 'from' address for the feedback_complete email to users
    config.x.organisation.do_not_reply_email = ENV['ORGANISATION_DO_NOT_REPLY_EMAIL']
    # This email is used in email communications
    config.x.organisation.helpdesk_email = ENV['ORGANISATION_HELPDESK_EMAIL']
    # Your organisation's telephone number - used on the contact us page
    config.x.organisation.telephone = ENV['ORGANISATION_TELEPHONE']
    # Your organisation's address - used on the contact us page
    # rubocop:disable Naming/VariableNumber
    config.x.organisation.address = {
      line_1: ENV['ORGANISATION_ADDRESS_LINE_1'],
      line_2: ENV['ORGANISATION_ADDRESS_LINE_2'],
      line_3: ENV['ORGANISATION_ADDRESS_LINE_3'],
      line_4: ENV['ORGANISATION_ADDRESS_LINE_4'],
      country: ENV['ORGANISATION_ADDRESS_COUNTRY']
    }
    # rubocop:enable Naming/VariableNumber

    # The Google maps link to your organisation's location - used to display the
    # Google map on the contact us page.
    # To find your organisation's Google maps URL, open maps.google.com, search for
    # your orgnaisation and then click the menu link to the left of the search box,
    # once the menu opens, click the 'share or embed' link and the 'embed' tab on
    # the dialog window that opens. DO NOT place the entire <iframe> tag below, just
    # the address!
    config.x.organisation.google_maps_link = ENV['ORGANISATION_GOOGLE_MAPS_LINK']

    # Uncomment the following line if you want to redirect your users to an
    # organisational contact/help page instead of using the built-in contact_us form
    # config.x.organisation.contact_us_url = "https://example.org/contact

    # -------------------- #
    # APPLICATION SETTINGS #
    # -------------------- #

    # Used throughout the system via ApplicationService.application_name
    config.x.application.name = ENV['APPLICATION_NAME']
    # Used as the default domain when 'archiving' (aka anonymizing) a user account
    # for example `jane.doe@uni.edu` becomes `1234@removed_accounts-example.org`
    config.x.application.archived_accounts_email_suffix = ENV['APPLICATION_ARCHIVED_ACCOUNTS_EMAIL_SUFFIX']
    # Available CSV separators, the default is ','
    config.x.application.csv_separators = [',', '|', '#']
    # The largest page size allowed in requests to the API (all versions)
    config.x.application.api_max_page_size = ENV['APPLICATION_API_MAX_PAGE_SIZE']
    # The link to the API documentation - used in emails about the API
    config.x.application.api_documentation_urls = {
      v0: ENV['APPLICATION_API_DOCUMENTATION_URLS_VO'],
      v1: ENV['APPLICATION_API_DOCUMENTATION_URLS_V1']
    }
    # The links that appear on the home page. Add any number of links
    config.x.application.welcome_links = [
      {
        title: ENV['APPLICATION_WELCOME_LINK_TITLE_1'],
        url: ENV['APPLICATION_WELCOME_LINK_URL_1']
      }, {
        title: ENV['APPLICATION_WELCOME_LINK_TITLE_2'],
        url: ENV['APPLICATION_WELCOME_LINK_URL_2']
      }, {
        title: ENV['APPLICATION_WELCOME_LINK_TITLE_3'],
        url: ENV['APPLICATION_WELCOME_LINK_URL_3']
      }, {
        title: ENV['APPLICATION_WELCOME_LINK_TITLE_4'],
        url: ENV['APPLICATION_WELCOME_LINK_URL_4']
      }, {
        title: ENV['APPLICATION_WELCOME_LINK_TITLE_5'],
        url: ENV['APPLICATION_WELCOME_LINK_URL_5']
      }
    ]
    # The default user email preferences used when a new account is created
    config.x.application.preferences = {
      email: {
        users: {
          new_comment: ENV['APPLICATION_PREFERENCES_NEW_COMMENT'],
          admin_privileges: ENV['APPLICATION_PREFERENCES_ADMIN_PRIVILEGES'],
          added_as_coowner: ENV['APPLICATION_PREFERENCES_ADDED_AS_COOWNER'],
          feedback_requested: ENV['APPLICATION_PREFERENCES_FEEDBACK_REQUESTED'],
          feedback_provided: ENV['APPLICATION_PREFERENCES_FEEDBACK_PROVIDED']
        },
        owners_and_coowners: {
          visibility_changed: ENV['APPLICATION_PREFERENCES_VISIBILITY_CHANGED']
        }
      }
    }
    # Setting to only take orgs from local and not allow on-the-fly creation
    config.x.application.restrict_orgs = ENV['APPLICATION_RESTRICT_ORGS']
    # Setting to display phone number in contributor form
    config.x.application.display_contributor_phone_number = ENV['APPLICATION_DISPLAY_CONTRIBUTOR_PHONE_NUMBER']

    # Setting require contributor requirement of contributor name and email
    config.x.application.require_contributor_name = ENV['APPLICATION_REQUIRE_CONTRIBUTOR_NAME']
    config.x.application.require_contributor_email = ENV['APPLICATION_REQUIRE_CONTRIBUTOR_EMAIL']

    # Defines if Guidances/Comments in toggleable & if it's opened by default
    config.x.application.guidance_comments_toggleable = ENV['APPLICATION_GUIDANCE_COMMENTS_TOGGLEABLE']
    config.x.application.guidance_comments_opened_by_default = ENV['APPLICATION_GUIDANCE_COMMENTS_OPENED_BY_DEFAULT']

    # ------------------- #
    # SHIBBOLETH SETTINGS #
    # ------------------- #

    # Enable shibboleth as an alternative authentication method
    # Requires server configuration and omniauth shibboleth provider configuration
    # See config/initializers/devise.rb
    config.x.shibboleth.enabled = true

    # Relative path to Shibboleth SSO Logouts
    config.x.shibboleth.login_url = '/Shibboleth.sso/Login'
    config.x.shibboleth.logout_url = '/Shibboleth.sso/Logout?return='

    # If this value is set to true your users will be presented with a list of orgs that have a
    # shibboleth identifier in the orgs_identifiers table. If it is set to false (default), the user
    # will be driven out to your federation's discovery service
    #
    # A super admin will also be able to associate orgs with their shibboleth entityIds if this is set to true
    config.x.shibboleth.use_filtered_discovery_service = false

    # ------- #
    # LOCALES #
    # ------- #

    # The default locale (use the i18n format!)
    config.x.locales.default = 'en-GB'
    # The character that separates a locale's ISO code for i18n. (e.g. `en-GB` or `en`)
    # Changing this value is not recommended!
    config.x.locales.i18n_join_character = '-'
    # The character that separates a locale's ISO code for Gettext. (e.g. `en_GB` or `en`)
    # Changing this value is not recommended!
    config.x.locales.gettext_join_character = '_'

    # ---------- #
    # THRESHOLDS #
    # ---------- #

    # Determines the number of links a funder is allowed to add to their template
    config.x.max_number_links_funder = 5
    # Determines the number of links a funder can add for sample plans for their template
    config.x.max_number_links_sample_plan = 5
    # Determines the maximum number of themes to display per column when an org admin
    # updates a template question or guidance
    config.x.max_number_themes_per_column = 5
    # default results per page
    config.x.results_per_page = 10

    # ------------- #
    # PLAN DEFAULTS #
    # ------------- #

    # The default visibility a plan receives when it is created.
    # options: 'privately_visible', 'organisationally_visible' and 'publicly_visibile'
    config.x.plans.default_visibility = 'privately_visible'

    # The percentage of answers that have been filled out that determine if a plan
    # will be marked as complete. Plan completion has implications on whether or
    # not plan visibility settings are editable by the user and whether or not the
    # plan can be submitted for feedback
    config.x.plans.default_percentage_answered = 50

    # Whether or not Super adminis can read all of the user's plans regardless of
    # the plans visibility and whether or not the plan has been shared
    config.x.plans.org_admins_read_all = true
    # Whether or not Organisational administrators can read all of the user's plans
    # regardless of the plans visibility and whether or not the plan has been shared
    config.x.plans.super_admins_read_all = true

    # Check download of a plan coversheet tickbox
    config.x.plans.download_coversheet_tickbox_checked = false

    # ---------------------------------------------------- #
    # CACHING - all values are in seconds (86400 == 1 Day) #
    # ---------------------------------------------------- #

    # Determines how long to cache results for OrgSelection::SearchService
    config.x.cache.org_selection_expiration = 86_400
    # Determines how long to cache results for the ResearchProjectsController
    config.x.cache.research_projects_expiration = 86_400

    # ---------------- #
    # Google Analytics #
    # ---------------- #
    # this is the abbreviation for the installation's root org as set in the org table
    config.x.google_analytics.tracker_root = ''

    # ------------------------------------------------------------------------ #
    # reCAPTCHA - recaptcha appears on the create account and contact us forms #
    # ------------------------------------------------------------------------ #
    config.x.recaptcha.enabled = false

    # --------------------------------------------------- #
    # Machine Actionable / Networked DMP Features (maDMP) #
    # --------------------------------------------------- #
    # Enable/disable functionality on the Project Details tab
    config.x.madmp.enable_ethical_issues = true
    config.x.madmp.enable_research_domain = true

    # This flag will enable/disable the entire Research Outputs tab. The others below will
    # just enable/disable specific functionality on the Research Outputs tab
    config.x.madmp.enable_research_outputs = true
    config.x.madmp.enable_license_selection = true
    config.x.madmp.enable_metadata_standard_selection = true
    config.x.madmp.enable_repository_selection = true

    # The following flags will allow the system to include the question and answer in the JSON output
    #   - questions with a theme equal to 'Preservation'
    config.x.madmp.extract_preservation_statements_from_themed_questions = false
    #   - questions with a theme equal to 'Data Collection'
    config.x.madmp.extract_data_quality_statements_from_themed_questions = false
    #   - questions with a theme equal to 'Ethics & privacy' or 'Storage & security'
    config.x.madmp.extract_security_privacy_statements_from_themed_questions = false

    # Specify a list of the preferred licenses types. These licenses will appear in a select
    # box on the 'Research Outputs' tab when editing a plan along with the option to select
    # 'other'. When 'other' is selected, the user is presented with the full list of licenses.
    #
    # The licenses will appear in the order you specify here.
    #
    # Note that the values you enter must match the :identifier field of the licenses table.
    # You can use the `%{latest}` markup in place of version numbers if desired.
    config.x.madmp.preferred_licenses = [
      'CC-BY-%{latest}',
      'CC-BY-SA-%{latest}',
      'CC-BY-NC-%{latest}',
      'CC-BY-NC-SA-%{latest}',
      'CC-BY-ND-%{latest}',
      'CC-BY-NC-ND-%{latest}',
      'CC0-%{latest}'
    ]
    # Link to external guidance about selecting one of the preferred licenses. A default
    # URL will be displayed if none is provided here. See app/views/research_outputs/licenses/_form
    config.x.madmp.preferred_licenses_guidance_url = 'https://creativecommons.org/about/cclicenses/'
  end

end