defaults: &defaults
  legal_entity: 'the University of Edinburgh, University of Glasgow and the University of California'

  # Warning: The abbreviation here should match the org.abbreviation value registered in your database!
  organisation: &organization_defaults
    name: 'Portage Network'
    abbreviation: 'Portage'  # This value is used to identify the default guidance that get auto-selected when a new plan is created
    url: 'https://github.com/DMPRoadmap/roadmap/wiki'
    copywrite_name: 'Portage Network'
    email: 'support@portagenetwork.ca'
    helpdesk_email: 'support@portagenetwork.ca'
    # XXX Need to update the welcome links
    welcome_links:
      - link1:
        title: 'Digital Curation Centre'
        url: 'https://dcc.ac.uk/'
      - link2:
        title: 'UC3: University of California Curation Center'
        url: 'https://www.cdlib.org/uc3/'
      - link3:
        title: 'UK funder requirements for Data Management Plans'
        url: 'http://www.dcc.ac.uk/resources/data-management-plans/funders-requirements'
      - link4:
        title: 'US funder requirements for Data Management Plans'
        url: 'https://dmptool.org/general_guidance'
      - link5:
        title: 'DCC Checklist for a Data Management Plan'
        url: 'https://dmponline.dcc.ac.uk/files/DMP_Checklist_2013.pdf'

    # Warning: this value will be used to override the URl of the application's built-in contact form. It will
    #          replace the link in all email communications as well as the contact link in the page footer!
    #
    #          Comment this line out if you want to use DMPRoadmap's built-in contact form.
    contact_us_url: 'https://portagenetwork.ca/contact-us/'

  application: &application_defaults
    name: 'DMP Assistant'
    url: 'https://github.com/portagenetwork/roadmap'
    version: '1.0.0'
    release_notes_url: 'https://github.com/portagenetwork/roadmap/wiki/Releases'
    issue_list_url: 'https://github.com/portagenetwork/roadmap/issues'
    user_group_subscription_url: 'http://listserv.ucop.edu/cgi-bin/wa.exe?SUBED1=ROADMAP-L&A=1'
    api_documentation_url: 'https://github.com/portagenetwork/roadmap/wiki/API-Documentation'
    api_max_page_size: 100
    archived_accounts_email_suffix: '@removed_accounts.org'

  preferences:
    email:
      users:
        new_comment: false
        admin_privileges: true
        added_as_coowner: true
        feedback_requested: true
        feedback_provided: true
      owners_and_coowners:
        visibility_changed: true

  service_configuration:
    plans:
      org_admins_read_all: true
      super_admins_read_all: true


development:
  <<: *defaults

test:
  <<: *defaults

stage:
  <<: *defaults

staging:
  <<: *defaults

uat:
  <<: *defaults

production:
  <<: *defaults
