# This is an example credentials file.
# To real credentials file is encrypted.
# To create it run
# EDITOR=my_ave_editor rails credentials:edit
# and paste the rest of this file in, filling in the correct values
#
# If you need to generate a new secret you can run the `rails secret` utility

database:
  host: "127.0.0.1"
  username: "roadmap_user"
  password: "roadmap_password"

devise_pepper: "C5vvrxyzKoXq4aeU0GxXgW2QhSgbXiJEXqlVxa0tFYNHSJNfydZnE0BeUPOnK12i"

dragonfly_secret: "my_secret"

recaptcha:
  site_key: "6LdRjtkZAAAAAP6hRvmduamdN5RtbmykUQwTp4UU"
  secret_key: "6LdRjtkZAAAAAKEyN_kvojQ3HyRPt3IQGYdIbuGV"

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: "my_secret"
