defaults: &defaults
  on_sandbox: <%= ENV.fetch('ON_SANDBOX_FEATURE', false) %>

development:
  <<: *defaults
test:
  <<: *defaults
  on_sandbox: FALSE
stage:
  <<: *defaults
staging:
  <<: *defaults
sandbox:
 <<: *defaults
uat:
  <<: *defaults
production:
  <<: *defaults