defaults: &defaults
  on_sandbox:  <%= Rails.application.secrets.feature_flag.on_sandbox %>
  

development:
  <<: *defaults
test:
  <<: *defaults
  on_sandbox: FALSE
staging:
  <<: *defaults
sandbox:
 <<: *defaults
uat:
  <<: *defaults
production:
  <<: *defaults