# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

test:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  database_url: <%= ENV['DATABASE_URL'] %>
  wicked_pdf_path: <%= ENV['WICKED_PDF_PATH'] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  mailer_from: <%= ENV['MAILER_FROM'] %>
  mailer_to: <%= ENV['MAILER_TO'] %>
  recaptcha_site_key: <%= ENV['RECAPTCHA_SITE_KEY'] %>
  recaptcha_secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
  orcid_client_id: <%= ENV['ORCID_CLIENT_ID'] %>
  orcid_client_secret: <%= ENV['ORCID_CLIENT_SECRET'] %>
  orcid_client_member: <%= ENV['ORCID_CLIENT_MEMBER'] %>
  mailer_default_host: <%= ENV['MAILER_DEFAULT_HOST'] || Socket.gethostname %>
  omniauth_full_host: <%= ENV['OMNIAUTH_FULL_HOST'] %>
  google_analytics_token: <%= ENV['GOOGLE_ANALYTICS_TOKEN'] %>
  wicked_pdf_proxy: <%= ENV['WICKED_PDF_PROXY'] %>

development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  database_url: <%= ENV['DATABASE_URL'] %>
  wicked_pdf_path: <%= ENV['WICKED_PDF_PATH'] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  mailer_from: <%= ENV['MAILER_FROM'] %>
  mailer_to: <%= ENV['MAILER_TO'] %>
  recaptcha_site_key: <%= ENV['RECAPTCHA_SITE_KEY'] %>
  recaptcha_secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
  orcid_client_id: <%= ENV['ORCID_CLIENT_ID'] %>
  orcid_client_secret: <%= ENV['ORCID_CLIENT_SECRET'] %>
  orcid_client_member: <%= ENV['ORCID_CLIENT_MEMBER'] %>
  mailer_default_host: <%= ENV['MAILER_DEFAULT_HOST'] || Socket.gethostname %>
  omniauth_full_host: <%= ENV['OMNIAUTH_FULL_HOST'] %>
  google_analytics_token: <%= ENV['GOOGLE_ANALYTICS_TOKEN'] %>
  wicked_pdf_proxy: <%= ENV['WICKED_PDF_PROXY'] %>

staging:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  database_url: <%= ENV['DATABASE_URL'] %>
  wicked_pdf_path: <%= ENV['WICKED_PDF_PATH'] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  mailer_from: <%= ENV['MAILER_FROM'] %>
  mailer_to: <%= ENV['MAILER_TO'] %>
  recaptcha_site_key: <%= ENV['RECAPTCHA_SITE_KEY'] %>
  recaptcha_secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
  orcid_client_id: <%= ENV['ORCID_CLIENT_ID'] %>
  orcid_client_secret: <%= ENV['ORCID_CLIENT_SECRET'] %>
  orcid_client_member: <%= ENV['ORCID_CLIENT_MEMBER'] %>
  mailer_default_host: <%= ENV['MAILER_DEFAULT_HOST'] %>
  omniauth_full_host: <%= ENV['OMNIAUTH_FULL_HOST'] %>
  google_analytics_token: <%= ENV['GOOGLE_ANALYTICS_TOKEN'] %>
  wicked_pdf_proxy: <%= ENV['WICKED_PDF_PROXY'] %>
  http_proxy: <%= ENV['HTTP_PROXY'] %>
  http_proxy_port: <%= ENV['HTTP_PROXY_PORT'] %>

uat:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  database_url: <%= ENV['DATABASE_URL'] %>
  wicked_pdf_path: <%= ENV['WICKED_PDF_PATH'] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  mailer_from: <%= ENV['MAILER_FROM'] %>
  mailer_to: <%= ENV['MAILER_TO'] %>
  recaptcha_site_key: <%= ENV['RECAPTCHA_SITE_KEY'] %>
  recaptcha_secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
  orcid_client_id: <%= ENV['ORCID_CLIENT_ID'] %>
  orcid_client_secret: <%= ENV['ORCID_CLIENT_SECRET'] %>
  orcid_client_member: <%= ENV['ORCID_CLIENT_MEMBER'] %>
  mailer_default_host: <%= ENV['MAILER_DEFAULT_HOST'] %>
  omniauth_full_host: <%= ENV['OMNIAUTH_FULL_HOST'] %>
  google_analytics_token: <%= ENV['GOOGLE_ANALYTICS_TOKEN'] %>
  wicked_pdf_proxy: <%= ENV['WICKED_PDF_PROXY'] %>
  http_proxy: <%= ENV['HTTP_PROXY'] %>
  http_proxy_port: <%= ENV['HTTP_PROXY_PORT'] %>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  database_url: <%= ENV['DATABASE_URL'] %>
  wicked_pdf_path: <%= ENV['WICKED_PDF_PATH'] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  mailer_from: <%= ENV['MAILER_FROM'] %>
  mailer_to: <%= ENV['MAILER_TO'] %>
  recaptcha_site_key: <%= ENV['RECAPTCHA_SITE_KEY'] %>
  recaptcha_secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
  orcid_client_id: <%= ENV['ORCID_CLIENT_ID'] %>
  orcid_client_secret: <%= ENV['ORCID_CLIENT_SECRET'] %>
  orcid_client_member: <%= ENV['ORCID_CLIENT_MEMBER'] %>
  mailer_default_host: <%= ENV['MAILER_DEFAULT_HOST'] %>
  omniauth_full_host: <%= ENV['OMNIAUTH_FULL_HOST'] %>
  google_analytics_token: <%= ENV['GOOGLE_ANALYTICS_TOKEN'] %>
  wicked_pdf_proxy: <%= ENV['WICKED_PDF_PROXY'] %>
  http_proxy: <%= ENV['HTTP_PROXY'] %>
  http_proxy_port: <%= ENV['HTTP_PROXY_PORT'] %>
