development: 
  database_url: "<%= ENV['DATABASE_URL'] %>"
  default_funder_name: "<%= ENV['DEFAULT_FUNDER_NAME'] %>"
  devise_pepper: "<%= ENV['DEVISE_PEPPER'] %>"
  devise_secret_key: "<%= ENV['DEVISE_SECRET_KEY'] %>"
  dragonfly_secret: "<%= ENV['DRAGONFLY_SECRET'] %>"
  english_admin_password: "<%= ENV['ENGLISH_ADMIN_PASSWORD'] %>"
  english_org_id: "<%= ENV['ENGLISH_ORG_ID'] %>"
  french_admin_password: "<%= ENV['FRENCH_ADMIN_PASSWORD'] %>"
  french_org_id: "<%= ENV['FRENCH_ORG_ID'] %>"
  funder_org_id: "<%= ENV['FUNDER_ORG_ID'] %>"
  google_analytics_token: "<%= ENV['GOOGLE_ANALYTICS_TOKEN'] %>"
  mailer_default_host: "<%= ENV['MAILER_DEFAULT_HOST'] || Socket.gethostname %>"
  mailer_from: "<%= ENV['MAILER_FROM'] %>"
  mailer_to: "<%= ENV['MAILER_TO'] %>"
  omniauth_full_host: "<%= ENV['OMNIAUTH_FULL_HOST'] %>"
  on_sandbox: "<%= ENV['ON_SANDBOX'] %>"
  orcid_client_id: "<%= ENV['ORCID_CLIENT_ID'] %>"
  orcid_client_member: "<%= ENV['ORCID_CLIENT_MEMBER'] %>"
  orcid_client_secret: "<%= ENV['ORCID_CLIENT_SECRET'] %>"
  recaptcha_secret_key: "<%= ENV['RECAPTCHA_SECRET_KEY'] %>"
  recaptcha_site_key: "<%= ENV['RECAPTCHA_SITE_KEY'] %>"
  rollbar_access_token: "<%= ENV['ROLLBAR_ACCESS_TOKEN'] %>"
  secret_key_base: "<%= ENV['SECRET_KEY_BASE'] %>"
  super_admin_password: "<%= ENV['SUPER_ADMIN_PASSWORD'] %>"
  test_password: "<%= ENV['TEST_PASSWORD'] %>"
  translation_io_api_key: "<%= ENV['TRANSLATION_IO_API_KEY'] %>"
  user_password: "<%= ENV['USER_PASSWORD'] %>"
  wicked_pdf_path: "<%= ENV['WICKED_PDF_PATH'] %>"
  wicked_pdf_proxy: "<%= ENV['WICKED_PDF_PROXY'] %>"

production: 
  database_url: "<%= ENV['DATABASE_URL'] %>"
  default_funder_name: "<%= ENV['DEFAULT_FUNDER_NAME'] %>"
  devise_pepper: "<%= ENV['DEVISE_PEPPER'] %>"
  devise_secret_key: "<%= ENV['DEVISE_SECRET_KEY'] %>"
  dragonfly_secret: "<%= ENV['DRAGONFLY_SECRET'] %>"
  english_admin_password: "<%= ENV['ENGLISH_ADMIN_PASSWORD'] %>"
  english_org_id: "<%= ENV['ENGLISH_ORG_ID'] %>"
  french_admin_password: "<%= ENV['FRENCH_ADMIN_PASSWORD'] %>"
  french_org_id: "<%= ENV['FRENCH_ORG_ID'] %>"
  funder_org_id: "<%= ENV['FUNDER_ORG_ID'] %>"
  google_analytics_token: "<%= ENV['GOOGLE_ANALYTICS_TOKEN'] %>"
  http_proxy: "<%= ENV['HTTP_PROXY'] %>"
  http_proxy_port: "<%= ENV['HTTP_PROXY_PORT'] %>"
  mailer_default_host: "<%= ENV['MAILER_DEFAULT_HOST'] %>"
  mailer_from: "<%= ENV['MAILER_FROM'] %>"
  mailer_to: "<%= ENV['MAILER_TO'] %>"
  omniauth_full_host: "<%= ENV['OMNIAUTH_FULL_HOST'] %>"
  on_sandbox: "<%= ENV['ON_SANDBOX'] %>"
  orcid_client_id: "<%= ENV['ORCID_CLIENT_ID'] %>"
  orcid_client_member: "<%= ENV['ORCID_CLIENT_MEMBER'] %>"
  orcid_client_secret: "<%= ENV['ORCID_CLIENT_SECRET'] %>"
  recaptcha_secret_key: "<%= ENV['RECAPTCHA_SECRET_KEY'] %>"
  recaptcha_site_key: "<%= ENV['RECAPTCHA_SITE_KEY'] %>"
  rollbar_access_token: "<%= ENV['ROLLBAR_ACCESS_TOKEN'] %>"
  secret_key_base: "<%= ENV['SECRET_KEY_BASE'] %>"
  smtp_address: "<%= ENV['SMTP_ADDRESS'] %>"
  smtp_authentication: "<%= ENV['SMTP_AUTHENTICATION'] %>"
  smtp_domain: "<%= ENV['SMTP_DOMAIN'] %>"
  smtp_password: "<%= ENV['SMTP_PASSWORD'] %>"
  smtp_port: "<%= ENV['SMTP_PORT'] %>"
  smtp_user_name: "<%= ENV['SMTP_USER_NAME'] %>"
  super_admin_password: "<%= ENV['SUPER_ADMIN_PASSWORD'] %>"
  test_password: "<%= ENV['TEST_PASSWORD'] %>"
  translation_io_api_key: "<%= ENV['TRANSLATION_IO_API_KEY'] %>"
  user_password: "<%= ENV['USER_PASSWORD'] %>"
  wicked_pdf_path: "<%= ENV['WICKED_PDF_PATH'] %>"
  wicked_pdf_proxy: "<%= ENV['WICKED_PDF_PROXY'] %>"

sandbox: 
  database_url: "<%= ENV['DATABASE_URL'] %>"
  default_funder_name: "<%= ENV['DEFAULT_FUNDER_NAME'] %>"
  devise_pepper: "<%= ENV['DEVISE_PEPPER'] %>"
  devise_secret_key: "<%= ENV['DEVISE_SECRET_KEY'] %>"
  dragonfly_secret: "<%= ENV['DRAGONFLY_SECRET'] %>"
  english_admin_password: "<%= ENV['ENGLISH_ADMIN_PASSWORD'] %>"
  english_org_id: "<%= ENV['ENGLISH_ORG_ID'] %>"
  french_admin_password: "<%= ENV['FRENCH_ADMIN_PASSWORD'] %>"
  french_org_id: "<%= ENV['FRENCH_ORG_ID'] %>"
  funder_org_id: "<%= ENV['FUNDER_ORG_ID'] %>"
  google_analytics_token: "<%= ENV['GOOGLE_ANALYTICS_TOKEN'] %>"
  http_proxy: "<%= ENV['HTTP_PROXY'] %>"
  http_proxy_port: "<%= ENV['HTTP_PROXY_PORT'] %>"
  mailer_default_host: "<%= ENV['MAILER_DEFAULT_HOST'] %>"
  mailer_from: "<%= ENV['MAILER_FROM'] %>"
  mailer_to: "<%= ENV['MAILER_TO'] %>"
  omniauth_full_host: "<%= ENV['OMNIAUTH_FULL_HOST'] %>"
  on_sandbox: "<%= ENV['ON_SANDBOX'] %>"
  orcid_client_id: "<%= ENV['ORCID_CLIENT_ID'] %>"
  orcid_client_member: "<%= ENV['ORCID_CLIENT_MEMBER'] %>"
  orcid_client_secret: "<%= ENV['ORCID_CLIENT_SECRET'] %>"
  recaptcha_secret_key: "<%= ENV['RECAPTCHA_SECRET_KEY'] %>"
  recaptcha_site_key: "<%= ENV['RECAPTCHA_SITE_KEY'] %>"
  rollbar_access_token: "<%= ENV['ROLLBAR_ACCESS_TOKEN'] %>"
  secret_key_base: "<%= ENV['SECRET_KEY_BASE'] %>"
  smtp_address: "<%= ENV['SMTP_ADDRESS'] %>"
  smtp_authentication: "<%= ENV['SMTP_AUTHENTICATION'] %>"
  smtp_domain: "<%= ENV['SMTP_DOMAIN'] %>"
  smtp_password: "<%= ENV['SMTP_PASSWORD'] %>"
  smtp_port: "<%= ENV['SMTP_PORT'] %>"
  smtp_user_name: "<%= ENV['SMTP_USER_NAME'] %>"
  super_admin_password: "<%= ENV['SUPER_ADMIN_PASSWORD'] %>"
  test_password: "<%= ENV['TEST_PASSWORD'] %>"
  translation_io_api_key: "<%= ENV['TRANSLATION_IO_API_KEY'] %>"
  user_password: "<%= ENV['USER_PASSWORD'] %>"
  wicked_pdf_path: "<%= ENV['WICKED_PDF_PATH'] %>"
  wicked_pdf_proxy: "<%= ENV['WICKED_PDF_PROXY'] %>"

staging: 
  database_url: "<%= ENV['DATABASE_URL'] %>"
  default_funder_name: "<%= ENV['DEFAULT_FUNDER_NAME'] %>"
  devise_pepper: "<%= ENV['DEVISE_PEPPER'] %>"
  devise_secret_key: "<%= ENV['DEVISE_SECRET_KEY'] %>"
  dragonfly_secret: "<%= ENV['DRAGONFLY_SECRET'] %>"
  english_admin_password: "<%= ENV['ENGLISH_ADMIN_PASSWORD'] %>"
  english_org_id: "<%= ENV['ENGLISH_ORG_ID'] %>"
  french_admin_password: "<%= ENV['FRENCH_ADMIN_PASSWORD'] %>"
  french_org_id: "<%= ENV['FRENCH_ORG_ID'] %>"
  funder_org_id: "<%= ENV['FUNDER_ORG_ID'] %>"
  google_analytics_token: "<%= ENV['GOOGLE_ANALYTICS_TOKEN'] %>"
  http_proxy: "<%= ENV['HTTP_PROXY'] %>"
  http_proxy_port: "<%= ENV['HTTP_PROXY_PORT'] %>"
  mailer_default_host: "<%= ENV['MAILER_DEFAULT_HOST'] %>"
  mailer_from: "<%= ENV['MAILER_FROM'] %>"
  mailer_to: "<%= ENV['MAILER_TO'] %>"
  omniauth_full_host: "<%= ENV['OMNIAUTH_FULL_HOST'] %>"
  on_sandbox: "<%= ENV['ON_SANDBOX'] %>"
  orcid_client_id: "<%= ENV['ORCID_CLIENT_ID'] %>"
  orcid_client_member: "<%= ENV['ORCID_CLIENT_MEMBER'] %>"
  orcid_client_secret: "<%= ENV['ORCID_CLIENT_SECRET'] %>"
  recaptcha_secret_key: "<%= ENV['RECAPTCHA_SECRET_KEY'] %>"
  recaptcha_site_key: "<%= ENV['RECAPTCHA_SITE_KEY'] %>"
  rollbar_access_token: "<%= ENV['ROLLBAR_ACCESS_TOKEN'] %>"
  secret_key_base: "<%= ENV['SECRET_KEY_BASE'] %>"
  smtp_address: "<%= ENV['SMTP_ADDRESS'] %>"
  smtp_authentication: "<%= ENV['SMTP_AUTHENTICATION'] %>"
  smtp_domain: "<%= ENV['SMTP_DOMAIN'] %>"
  smtp_password: "<%= ENV['SMTP_PASSWORD'] %>"
  smtp_port: "<%= ENV['SMTP_PORT'] %>"
  smtp_user_name: "<%= ENV['SMTP_USER_NAME'] %>"
  super_admin_password: "<%= ENV['SUPER_ADMIN_PASSWORD'] %>"
  test_password: "<%= ENV['TEST_PASSWORD'] %>"
  translation_io_api_key: "<%= ENV['TRANSLATION_IO_API_KEY'] %>"
  user_password: "<%= ENV['USER_PASSWORD'] %>"
  wicked_pdf_path: "<%= ENV['WICKED_PDF_PATH'] %>"
  wicked_pdf_proxy: "<%= ENV['WICKED_PDF_PROXY'] %>"

test: 
  database_test_url: "<%= ENV['DATABASE_TEST_URL'] %>"
  default_funder_name: "<%= ENV['DEFAULT_FUNDER_NAME'] %>"
  devise_pepper: "<%= ENV['DEVISE_PEPPER'] %>"
  devise_secret_key: "<%= ENV['DEVISE_SECRET_KEY'] %>"
  dragonfly_secret: "<%= ENV['DRAGONFLY_SECRET'] %>"
  english_admin_password: "<%= ENV['ENGLISH_ADMIN_PASSWORD'] %>"
  english_org_id: "<%= ENV['ENGLISH_ORG_ID'] %>"
  french_admin_password: "<%= ENV['FRENCH_ADMIN_PASSWORD'] %>"
  french_org_id: "<%= ENV['FRENCH_ORG_ID'] %>"
  funder_org_id: "<%= ENV['FUNDER_ORG_ID'] %>"
  google_analytics_token: "<%= ENV['GOOGLE_ANALYTICS_TOKEN'] %>"
  mailer_default_host: "<%= ENV['MAILER_DEFAULT_HOST'] || Socket.gethostname %>"
  mailer_from: "<%= ENV['MAILER_FROM'] %>"
  mailer_to: "<%= ENV['MAILER_TO'] %>"
  omniauth_full_host: "<%= ENV['OMNIAUTH_FULL_HOST'] %>"
  on_sandbox: "<%= ENV['ON_SANDBOX'] %>"
  orcid_client_id: "<%= ENV['ORCID_CLIENT_ID'] %>"
  orcid_client_member: "<%= ENV['ORCID_CLIENT_MEMBER'] %>"
  orcid_client_secret: "<%= ENV['ORCID_CLIENT_SECRET'] %>"
  recaptcha_secret_key: "<%= ENV['RECAPTCHA_SECRET_KEY'] %>"
  recaptcha_site_key: "<%= ENV['RECAPTCHA_SITE_KEY'] %>"
  rollbar_access_token: "<%= ENV['ROLLBAR_ACCESS_TOKEN'] %>"
  secret_key_base: "<%= ENV['SECRET_KEY_BASE'] %>"
  super_admin_password: "<%= ENV['SUPER_ADMIN_PASSWORD'] %>"
  test_password: "<%= ENV['TEST_PASSWORD'] %>"
  translation_io_api_key: "<%= ENV['TRANSLATION_IO_API_KEY'] %>"
  user_password: "<%= ENV['USER_PASSWORD'] %>"
  wicked_pdf_path: "<%= ENV['WICKED_PDF_PATH'] %>"
  wicked_pdf_proxy: "<%= ENV['WICKED_PDF_PROXY'] %>"
  
uat: 
  database_url: "<%= ENV['DATABASE_URL'] %>"
  default_funder_name: "<%= ENV['DEFAULT_FUNDER_NAME'] %>"
  devise_pepper: "<%= ENV['DEVISE_PEPPER'] %>"
  devise_secret_key: "<%= ENV['DEVISE_SECRET_KEY'] %>"
  dragonfly_secret: "<%= ENV['DRAGONFLY_SECRET'] %>"
  english_admin_password: "<%= ENV['ENGLISH_ADMIN_PASSWORD'] %>"
  english_org_id: "<%= ENV['ENGLISH_ORG_ID'] %>"
  french_admin_password: "<%= ENV['FRENCH_ADMIN_PASSWORD'] %>"
  french_org_id: "<%= ENV['FRENCH_ORG_ID'] %>"
  funder_org_id: "<%= ENV['FUNDER_ORG_ID'] %>"
  google_analytics_token: "<%= ENV['GOOGLE_ANALYTICS_TOKEN'] %>"
  http_proxy: "<%= ENV['HTTP_PROXY'] %>"
  http_proxy_port: "<%= ENV['HTTP_PROXY_PORT'] %>"
  mailer_default_host: "<%= ENV['MAILER_DEFAULT_HOST'] %>"
  mailer_from: "<%= ENV['MAILER_FROM'] %>"
  mailer_to: "<%= ENV['MAILER_TO'] %>"
  omniauth_full_host: "<%= ENV['OMNIAUTH_FULL_HOST'] %>"
  on_sandbox: "<%= ENV['ON_SANDBOX'] %>"
  orcid_client_id: "<%= ENV['ORCID_CLIENT_ID'] %>"
  orcid_client_member: "<%= ENV['ORCID_CLIENT_MEMBER'] %>"
  orcid_client_secret: "<%= ENV['ORCID_CLIENT_SECRET'] %>"
  recaptcha_secret_key: "<%= ENV['RECAPTCHA_SECRET_KEY'] %>"
  recaptcha_site_key: "<%= ENV['RECAPTCHA_SITE_KEY'] %>"
  rollbar_access_token: "<%= ENV['ROLLBAR_ACCESS_TOKEN'] %>"
  secret_key_base: "<%= ENV['SECRET_KEY_BASE'] %>"
  smtp_address: "<%= ENV['SMTP_ADDRESS'] %>"
  smtp_authentication: "<%= ENV['SMTP_AUTHENTICATION'] %>"
  smtp_domain: "<%= ENV['SMTP_DOMAIN'] %>"
  smtp_password: "<%= ENV['SMTP_PASSWORD'] %>"
  smtp_port: "<%= ENV['SMTP_PORT'] %>"
  smtp_user_name: "<%= ENV['SMTP_USER_NAME'] %>"
  super_admin_password: "<%= ENV['SUPER_ADMIN_PASSWORD'] %>"
  test_password: "<%= ENV['TEST_PASSWORD'] %>"
  translation_io_api_key: "<%= ENV['TRANSLATION_IO_API_KEY'] %>"
  user_password: "<%= ENV['USER_PASSWORD'] %>"
  wicked_pdf_path: "<%= ENV['WICKED_PDF_PATH'] %>"
  wicked_pdf_proxy: "<%= ENV['WICKED_PDF_PROXY'] %>"
