# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

test:
  database_test_url: <%= ENV['DATABASE_TEST_URL'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  dragonfly_secret: <%= ENV['DRAGONFLY_SECRET'] %>
  google_analytics_token: <%= ENV['GOOGLE_ANALYTICS_TOKEN'] %>
  mailer_default_host: <%= ENV['MAILER_DEFAULT_HOST'] || Socket.gethostname %>
  mailer_from: <%= ENV['MAILER_FROM'] %>
  mailer_to: <%= ENV['MAILER_TO'] %>
  omniauth_full_host: <%= ENV['OMNIAUTH_FULL_HOST'] %>
  orcid_client_id: <%= ENV['ORCID_CLIENT_ID'] %>
  orcid_client_member: <%= ENV['ORCID_CLIENT_MEMBER'] %>
  orcid_client_secret: <%= ENV['ORCID_CLIENT_SECRET'] %>
  recaptcha_secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
  recaptcha_site_key: <%= ENV['RECAPTCHA_SITE_KEY'] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  translation_io_api_key: <%= ENV['TRANSLATION_IO_API_KEY'] %>
  wicked_pdf_path: <%= ENV['WICKED_PDF_PATH'] %>
  wicked_pdf_proxy: <%= ENV['WICKED_PDF_PROXY'] %>
  default_funder_name: <%= ENV['DEFAULT_FUNDER_NAME'] %>

development:
  database_url: <%= ENV['DATABASE_URL'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  dragonfly_secret: <%= ENV['DRAGONFLY_SECRET'] %>
  google_analytics_token: <%= ENV['GOOGLE_ANALYTICS_TOKEN'] %>
  mailer_default_host: <%= ENV['MAILER_DEFAULT_HOST'] || Socket.gethostname %>
  mailer_from: <%= ENV['MAILER_FROM'] %>
  mailer_to: <%= ENV['MAILER_TO'] %>
  omniauth_full_host: <%= ENV['OMNIAUTH_FULL_HOST'] %>
  orcid_client_id: <%= ENV['ORCID_CLIENT_ID'] %>
  orcid_client_member: <%= ENV['ORCID_CLIENT_MEMBER'] %>
  orcid_client_secret: <%= ENV['ORCID_CLIENT_SECRET'] %>
  recaptcha_secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
  recaptcha_site_key: <%= ENV['RECAPTCHA_SITE_KEY'] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  translation_io_api_key: <%= ENV['TRANSLATION_IO_API_KEY'] %>
  wicked_pdf_path: <%= ENV['WICKED_PDF_PATH'] %>
  wicked_pdf_proxy: <%= ENV['WICKED_PDF_PROXY'] %>
  default_funder_name: <%= ENV['DEFAULT_FUNDER_NAME'] %>
  
staging:
  database_url: <%= ENV['DATABASE_URL'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  dragonfly_secret: <%= ENV['DRAGONFLY_SECRET'] %>
  google_analytics_token: <%= ENV['GOOGLE_ANALYTICS_TOKEN'] %>
  http_proxy: <%= ENV['HTTP_PROXY'] %>
  http_proxy_port: <%= ENV['HTTP_PROXY_PORT'] %>
  mailer_default_host: <%= ENV['MAILER_DEFAULT_HOST'] %>
  mailer_from: <%= ENV['MAILER_FROM'] %>
  mailer_to: <%= ENV['MAILER_TO'] %>
  omniauth_full_host: <%= ENV['OMNIAUTH_FULL_HOST'] %>
  orcid_client_id: <%= ENV['ORCID_CLIENT_ID'] %>
  orcid_client_member: <%= ENV['ORCID_CLIENT_MEMBER'] %>
  orcid_client_secret: <%= ENV['ORCID_CLIENT_SECRET'] %>
  recaptcha_secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
  recaptcha_site_key: <%= ENV['RECAPTCHA_SITE_KEY'] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  smtp_address: <%= ENV['SMTP_ADDRESS'] %>
  smtp_authentication: <%= ENV['SMTP_AUTHENTICATION'] %>
  smtp_domain: <%= ENV['SMTP_DOMAIN'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  smtp_port: <%= ENV['SMTP_PORT'] %>
  smtp_user_name: <%= ENV['SMTP_USER_NAME'] %>
  translation_io_api_key: <%= ENV['TRANSLATION_IO_API_KEY'] %>
  wicked_pdf_path: <%= ENV['WICKED_PDF_PATH'] %>
  wicked_pdf_proxy: <%= ENV['WICKED_PDF_PROXY'] %>
  default_funder_name: <%= ENV['DEFAULT_FUNDER_NAME'] %>

uat:
  database_url: <%= ENV['DATABASE_URL'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  dragonfly_secret: <%= ENV['DRAGONFLY_SECRET'] %>
  google_analytics_token: <%= ENV['GOOGLE_ANALYTICS_TOKEN'] %>
  http_proxy: <%= ENV['HTTP_PROXY'] %>
  http_proxy_port: <%= ENV['HTTP_PROXY_PORT'] %>
  mailer_default_host: <%= ENV['MAILER_DEFAULT_HOST'] %>
  mailer_from: <%= ENV['MAILER_FROM'] %>
  mailer_to: <%= ENV['MAILER_TO'] %>
  omniauth_full_host: <%= ENV['OMNIAUTH_FULL_HOST'] %>
  orcid_client_id: <%= ENV['ORCID_CLIENT_ID'] %>
  orcid_client_member: <%= ENV['ORCID_CLIENT_MEMBER'] %>
  orcid_client_secret: <%= ENV['ORCID_CLIENT_SECRET'] %>
  recaptcha_secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
  recaptcha_site_key: <%= ENV['RECAPTCHA_SITE_KEY'] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  smtp_address: <%= ENV['SMTP_ADDRESS'] %>
  smtp_authentication: <%= ENV['SMTP_AUTHENTICATION'] %>
  smtp_domain: <%= ENV['SMTP_DOMAIN'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  smtp_port: <%= ENV['SMTP_PORT'] %>
  smtp_user_name: <%= ENV['SMTP_USER_NAME'] %>
  translation_io_api_key: <%= ENV['TRANSLATION_IO_API_KEY'] %>
  wicked_pdf_path: <%= ENV['WICKED_PDF_PATH'] %>
  wicked_pdf_proxy: <%= ENV['WICKED_PDF_PROXY'] %>
  default_funder_name: <%= ENV['DEFAULT_FUNDER_NAME'] %>

sandbox:
  database_url: <%= ENV['DATABASE_URL'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  dragonfly_secret: <%= ENV['DRAGONFLY_SECRET'] %>
  google_analytics_token: <%= ENV['GOOGLE_ANALYTICS_TOKEN'] %>
  http_proxy: <%= ENV['HTTP_PROXY'] %>
  http_proxy_port: <%= ENV['HTTP_PROXY_PORT'] %>
  mailer_default_host: <%= ENV['MAILER_DEFAULT_HOST'] %>
  mailer_from: <%= ENV['MAILER_FROM'] %>
  mailer_to: <%= ENV['MAILER_TO'] %>
  omniauth_full_host: <%= ENV['OMNIAUTH_FULL_HOST'] %>
  orcid_client_id: <%= ENV['ORCID_CLIENT_ID'] %>
  orcid_client_member: <%= ENV['ORCID_CLIENT_MEMBER'] %>
  orcid_client_secret: <%= ENV['ORCID_CLIENT_SECRET'] %>
  recaptcha_secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
  recaptcha_site_key: <%= ENV['RECAPTCHA_SITE_KEY'] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  smtp_address: <%= ENV['SMTP_ADDRESS'] %>
  smtp_authentication: <%= ENV['SMTP_AUTHENTICATION'] %>
  smtp_domain: <%= ENV['SMTP_DOMAIN'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  smtp_port: <%= ENV['SMTP_PORT'] %>
  smtp_user_name: <%= ENV['SMTP_USER_NAME'] %>
  translation_io_api_key: <%= ENV['TRANSLATION_IO_API_KEY'] %>
  wicked_pdf_path: <%= ENV['WICKED_PDF_PATH'] %>
  wicked_pdf_proxy: <%= ENV['WICKED_PDF_PROXY'] %>
  default_funder_name: <%= ENV['DEFAULT_FUNDER_NAME'] %>

production:
  database_url: <%= ENV['DATABASE_URL'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  dragonfly_secret: <%= ENV['DRAGONFLY_SECRET'] %>
  google_analytics_token: <%= ENV['GOOGLE_ANALYTICS_TOKEN'] %>
  http_proxy: <%= ENV['HTTP_PROXY'] %>
  http_proxy_port: <%= ENV['HTTP_PROXY_PORT'] %>
  mailer_default_host: <%= ENV['MAILER_DEFAULT_HOST'] %>
  mailer_from: <%= ENV['MAILER_FROM'] %>
  mailer_to: <%= ENV['MAILER_TO'] %>
  omniauth_full_host: <%= ENV['OMNIAUTH_FULL_HOST'] %>
  orcid_client_id: <%= ENV['ORCID_CLIENT_ID'] %>
  orcid_client_member: <%= ENV['ORCID_CLIENT_MEMBER'] %>
  orcid_client_secret: <%= ENV['ORCID_CLIENT_SECRET'] %>
  recaptcha_secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
  recaptcha_site_key: <%= ENV['RECAPTCHA_SITE_KEY'] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  smtp_address: <%= ENV['SMTP_ADDRESS'] %>
  smtp_authentication: <%= ENV['SMTP_AUTHENTICATION'] %>
  smtp_domain: <%= ENV['SMTP_DOMAIN'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  smtp_port: <%= ENV['SMTP_PORT'] %>
  smtp_user_name: <%= ENV['SMTP_USER_NAME'] %>
  translation_io_api_key: <%= ENV['TRANSLATION_IO_API_KEY'] %>
  wicked_pdf_path: <%= ENV['WICKED_PDF_PATH'] %>
  wicked_pdf_proxy: <%= ENV['WICKED_PDF_PROXY'] %>
  default_funder_name: <%= ENV['DEFAULT_FUNDER_NAME'] %>