inherit_from: ../../.rubocop.yml

# Our controller actions tend to do a lot so increasing these to accommodate
# TODO: Refactor the code so we default back to the root .rubocop.yml rules
Metrics/AbcSize:
  Max: 45

Metrics/BlockNesting:
  Max: 6

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/MethodLength:
  Max: 60

Metrics/PerceivedComplexity:
  Max: 25
