name: ESLint

on: [push, pull_request]

jobs:
  eslint:

    runs-on: ubuntu-24.04

    steps:
    # Checkout the repo
    - uses: actions/checkout@v3

    # Install Node
    - uses: actions/setup-node@v3
      with:
        cache: 'yarn'
        node-version: 22

    # Run yarn install for JS dependencies
    - name: 'Yarn Install'
      run: yarn install

    - name: 'Run ESLint'
      run: yarn run eslint app/javascript/**/*.js --ext .js
