name: ESLint

on: [push, pull_request]

jobs:
  eslint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: eslint './app/javascript/**/*.js' --ext .js,.jsx,.ts,.tsx
