name: ESLint

on: [push, pull_request]

jobs:
  eslint:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn run eslint ./app/javascript/**/*.js
