name: ESLint

on: [push, pull_request]

jobs:
  eslint:

    runs-on: ubuntu-24.04

    steps:
    # Checkout the repo
    - uses: actions/checkout@v5

    # Install Node
    - uses: actions/setup-node@v5
      with:
        cache: 'yarn'
        node-version: 24

    # Run yarn install for JS dependencies
    - name: 'Yarn Install'
      run: yarn install --frozen-lockfile

    - name: 'Run ESLint'
      run: yarn lint

    - name: 'Run JavaScript tests'
      run: yarn test --reporters dots

    - name: 'Build CSS'
      run: yarn build:css
