name: ESLint

on: [pull_request]

jobs:
  eslint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # Will run ES Lint checks on javascript files
    #   https://github.com/marketplace/actions/run-eslint
    - uses: stefanoeb/eslint-action@1.0.0
        with:
          args: './app/javascript/**/*.js'
