name: DMPRoadmap tests

on:
  pull_request:
    branches: 
      - master
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install db packages
      run: |
        sudo apt-get update
        sudo apt-get install libmysqlclient-dev postgresql postgresql-contrib libpq-dev
        
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x

    - name: Install gems
      run: |
        gem install bundler -v 1.17.2
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3 --with development,ci --without pgsql,rollbar,aws

    - name: Install Webpack Dependencies
      run: yarn install

    - name: Setup default configs
      env:
        WICKED_PDF_PATH: ./vendor/bundle/ruby/2.4.0/bin/wkhtmltopdf
      run: |
        cp config/branding.yml.sample config/branding.yml
        cp config/database.yml.sample config/database.yml
        cp config/secrets.yml.sample config/secrets.yml
        cp config/initializers/contact_us.rb.example config/initializers/contact_us.rb
        cp config/initializers/devise.rb.example config/initializers/devise.rb
        cp config/initializers/recaptcha.rb.example config/initializers/recaptcha.rb
        cp config/initializers/wicked_pdf.rb.example config/initializers/wicked_pdf.rb
        bundle exec rake webpacker:compile
        bundle exec rake assets:precompile
        bin/rake db:setup

    - name: Run Rubocop
      run: bundle exec rubocop --parallel

    - name: Run Tests
      run: 
        bundle exec rspec spec/
