# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ deployment-portage ]
  pull_request:
    branches: [ deployment-portage ]

jobs:
  test:

    runs-on: ubuntu-latest    
    steps:

    - uses: actions/checkout@v2

    - name: 'Install MySQL Packages'
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client-core-8.0 
        sudo apt-get install -y mysql-server
        sudo apt-get install -y libmysqlclient-dev 

    - name: 'Start MySQL'
      run: |
        sudo systemctl unmask mysql
        sudo systemctl start mysql

    - name: 'Setup Test DB'
      run: bin/rails db:setup RAILS_ENV=test

    - name: 'Migrate DB'
      run: bin/rails db:migrate RAILS_ENV=test

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.3

    - name: Install dependencies
      run: bundle install

    - name: Run tests
      run: bundle exec rake spec
