name: CI

on:
  push:
    branches: [ deployment-portage ]
  pull_request:
    branches: [ deployment-portage ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.8
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake spec