name: Ruby

on:
  pull_request:
    branches: 
      - master
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.4
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x
    - name: Setup DMPRoadmap config
      env:
        key: WICKED_PDF_PATH=./vendor/bundle/ruby/2.4.0/bin/wkhtmltopdf
      run: bin/setup
    - name: Build and test with Rspec
      run: |
        gem install bundler
        bundle exec rake webpacker:compile
        bundle exec rake assets:precompile
        bundle install --jobs 4 --retry 3
        yarn install
        bundle exec rspec
