name: Rubocop

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
        
    # Will run Rubocop checks on the PR diffs and report any errors as commentary on the PR
    - name: Octocop
      uses: Freshly/Octocop@v0.0.1
      with:
        github_token: ${{ secrets.github_token }}
        rubocop_flags: "-c ./rubocop.yml"
