name: Run Tests

on:
  pull_request:
    branches: 
      - master
      - development

jobs:
  postgresql:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: 'Setup Postgresql'
      uses: ./.github/actions/postgresql@latest
    
    - name: Set up Ruby 2.4
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x
    
    - name: 'Build'
      uses: ./.github/actions/bundle@latest
      with: 
        database: postgresql
      
    - name: Cache Gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
          
    - name: Cache Yarn
      uses: actions/cache@v1
      with:
        path: node_modules/
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    
    - name: Setup Default Configuration
      uses: ./.github/actions/configure@latest

    - name: Run Rspec
      run: bundle exec rspec spec/
        
    - name: Run Karma
      run: yarn test
