name: Run Tests

on:
  pull_request:
    branches: 
      - master
      - development

jobs:
  postgresql:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    
    - name: 'Setup Postgresql'
      run: |
        sudo apt-get update
        sudo apt-get install libpq-dev
    
    - name: Set up Ruby 2.4
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x
    
    - name: 'Setup Default Configuration'
      run: |
        # Make copies of all the example config files
        cp config/branding.yml.sample config/branding.yml
        cp config/database.yml.sample config/database.yml
        cp config/secrets.yml.sample config/secrets.yml
        cp config/initializers/contact_us.rb.example config/initializers/contact_us.rb
        cp config/initializers/devise.rb.example config/initializers/devise.rb
        cp config/initializers/recaptcha.rb.example config/initializers/recaptcha.rb
        cp config/initializers/wicked_pdf.rb.example config/initializers/wicked_pdf.rb

    - name: 'Install Dependencies'
      run: |
        gem install bundler -v 1.17.2
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3 --without mysql rollbar aws
        yarn install
        bundle exec rake webpacker:compile
        bundle exec rake assets:precompile
      
    - name: 'Cache Gems'
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
          
    - name: 'Cache Yarn Packages'
      uses: actions/cache@v1
      with:
        path: node_modules/
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    
    - name: 'Run Karma Tests'
      run: yarn test

    - name: 'Run Rspec Tests'
      run: bundle exec rspec spec/
